language: bash
install:
    - sudo apt-get -qq install devscripts
before_script:
    - curl -L "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz" | tar zx
script:
    - bash shunit2/equality_test.sh
    - checkbashisms posix/testPosix.sh
