language: bash
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get -qq install devscripts
    - sudo pip install bashate
      # TODO travis上ではapt-getで取得できない
    # - sudo apt-get -qq install cabal-install
    - sudo apt-get -qq install shellcheck

    # - cabal update
    # - cabal install shellcheck
before_script:
    - curl -L "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz" | tar zx
script:
    # Static tests
    - checkbashisms ./posix/testPosix.sh
    - bashate ./posix/testPosix.sh
    # - ~/.cabal/bin/shellcheck ./posix/testPosix.sh
    - shellcheck ./posix/testPosix.sh

    # Unit tests
    - bash ./shunit2/equality_test.sh
